### ISSUE TITLE
Combine multiline string

### ISSUE THREAD

**Issue by mschoettle** [peschmae/glab-component-generator#1]
Very handy component, thanks a lot for this!

I have a multiline description which unfortunately does not get output properly for Markdown:

```yaml
description: |
        Since currently components do neither give some meta information nor deliver additional files we need the information to do this manually.
        The version supplied must be a valid git branch/tag and match the version of the component.
```

Output:

```markdown
| `component-version` | Since currently components do neither give some meta information nor deliver additional files we need the information to do this manually.
The version supplied must be a valid git branch/tag and match the version of the component.
 | _main_        |
```

One other things that I will squeeze in here: My repo also contains good old templates which get treated as components and produce a table with only the header. Is it possible to exclude those?

**Comment by peschmae** [comment]
Thanks :)

I've just released a new version 0.7.0 that includes support for multiline descriptions.
As it's rendered to HTML in GitLab, it now replaces the linebreaks with a `<br>` tag.

Additionally I've also made sure that components that would only result in a header beeing printed, are skipped. This should also exclude the good old templates.
